### ISSUE TITLE
MSI does not install over existing installation

### ISSUE THREAD

**Issue by wjreindersLogicx** [CrossBreezeNL/PowerDesigner-OData-AddIn#12]
When an older version is installed I get this message when installing:

![afbeelding](https://user-images.githubusercontent.com/80835698/201868881-3eaf6360-9eeb-4d0b-baf8-0331eb875255.png)

**Comment by harmen-xb** [comment]
@wjreindersLogicx Did this error occur with the latest MSI installation, while still having the previous version installed?

Because with the latest release we switch with versioning to v0.3.0, while the installer previously was always v1.0.0. So it might be that this error occurred because with the the new installation you are trying to install v0.3.0 over v1.0.0.

If this is the case, let's test with the next release whether this issue still occurs.

**Comment by harmen-xb** [comment]
@wjreindersLogicx Can you test with the newest MSI (https://github.com/CrossBreezeNL/PowerDesigner-OData-AddIn/releases/tag/v0.4.0-beta) whether this issue is solved?

**Comment by wjreindersLogicx** [comment]
@harmen-xb  : With v0.4.0 this issue is NOT resolved.

**Comment by harmen-xb** [comment]
@wjreindersLogicx Did you now uninstall v0.3.0 before installing v0.4.0 to be able to install?

**Comment by wjreindersLogicx** [comment]
Yes I first did an uninstall



​Met vriendelijke groet,
​
Willem Jan Reinders
I&T Architect - BI Specialist | Logicx Mobiliteit BV  | 
055 - 369 4078 | m 06 - 8352 2672 | 
Boogschutterstraat 7b, 7324AE 
Apeldoorn 
Postbus 4119,
 
7320AC Apeldoorn 
 | 
e ***@***.*** | w https://www.logicx.nl
Van: Harmen Wessels ***@***.***>
Verzonden: donderdag 23 februari 2023 12:03
Aan: CrossBreezeNL/PowerDesigner-OData-AddIn ***@***.***>
CC: Willem Jan Reinders ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [CrossBreezeNL/PowerDesigner-OData-AddIn] MSI does not install over existing installation (Issue #12)


@wjreindersLogicx<https://github.com/wjreindersLogicx> Did you now uninstall v0.3.0 before installing v0.4.0 to be able to install?

**Comment by harmen-xb** [comment]
As of release v0.5.1 the installer will uninstall the previous version to overcome this issue: https://github.com/CrossBreezeNL/PowerDesigner-OData-AddIn/releases/tag/v0.5.1
